version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.1
commands:
  init:
    description: 'sets up the environment'
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}
            - yarn-cache-master
      - run:
          name: install dependencies
          command: |
            yarn --pure-lockfile
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ .BuildNum }}
          paths:
            - /home/circleci/.cache/yarn/v1
      - run:
          name: build
          command: yarn build
jobs:
  test:
    docker:
      - image: 'cimg/node:15.8.0-browsers'
    steps:
      - browser-tools/install-browser-tools
      - init
      - run:
          name: unit tests
          command: yarn test
  deploy:
    docker:
      - image: 'cimg/node:15.8.0-browsers'
    steps:
      - browser-tools/install-browser-tools
      - init
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: deploy
          command: ./bin/deploy.sh
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
